Repository CS2103JAN2018-W14-B3/main, pull requests merged in 2018-04, with the labels that each got.

#68 Improve filter command III
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterUtil.java
  src/main/java/seedu/address/model/person/GradePointAverage.java
  src/main/java/seedu/address/model/person/GradePointAverageInKeywordsRangePredicate.java
  src/main/java/seedu/address/model/person/InterviewDateInKeywordsRangePredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/InterviewDateUtil.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterUtilTest.java
  src/test/java/seedu/address/model/person/ExpectedGraduationYearTest.java
  src/test/java/seedu/address/model/person/GradePointAverageInKeywordsRangePredicateTest.java
  src/test/java/seedu/address/model/person/InterviewDateInKeywordsRangePredicateTest.java
  src/test/java/seedu/address/model/util/InterviewDateUtilTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/FilterCommandSystemTest.java
Labels: priority.high, status.ready, type.enhancement

#71 Extend current rating-sort to a generic sort command that supports sorting by name, gpa and overall rating
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/RatingSortCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RatingSortCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: status.ready, type.enhancement

#73 V1.4 documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.documentation

#74 Collate code and update documentation
  README.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/commands/RatingDeleteCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RateCommandParser.java
  src/main/java/seedu/address/logic/parser/RatingDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/RateCommandTest.java
  src/test/java/seedu/address/logic/commands/RatingDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/RateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RatingDeleteCommandParserTest.java
  src/test/java/seedu/address/model/person/JobAppliedTest.java
  src/test/java/seedu/address/model/person/RatingTest.java
  src/test/java/seedu/address/model/person/UniversityTest.java
Labels: collate, type.documentation

#75 V1.4 collation
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterRange.java
  src/main/java/seedu/address/logic/parser/FilterUtil.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StatusCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/ExpectedGraduationYear.java
  src/main/java/seedu/address/model/person/ExpectedGraduationYearInKeywordsRangePredicate.java
  src/main/java/seedu/address/model/person/GradePointAverageInKeywordsRangePredicate.java
  src/main/java/seedu/address/model/person/InterviewDateInKeywordsRangePredicate.java
  src/main/java/seedu/address/model/person/RatingInKeywordsRangePredicate.java
  src/main/java/seedu/address/model/person/Resume.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/model/util/InterviewDateUtil.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterUtilTest.java
  src/test/java/seedu/address/logic/parser/StatusCommandParserTest.java
  src/test/java/seedu/address/model/person/ExpectedGraduationYearInKeywordsRangePredicateTest.java
  src/test/java/seedu/address/model/person/ExpectedGraduationYearTest.java
  src/test/java/seedu/address/model/person/InterviewDateInKeywordsRangePredicateTest.java
  src/test/java/seedu/address/model/person/RatingInKeywordsRangePredicateTest.java
  src/test/java/seedu/address/model/person/ResumeTest.java
  src/test/java/seedu/address/model/person/StatusTest.java
  src/test/java/seedu/address/model/util/InterviewDateUtilTest.java
Labels: collate

#79 v1.4 documentation
  docs/UserGuide.adoc
Labels: type.documentation, type.task

#82 Added collated files
  collated/functional/Ang-YC.md
  collated/functional/kexiaowen.md
  collated/functional/mhq199657.md
  collated/functional/tanhengyeow.md
  collated/test/Ang-YC.md
  collated/test/kexiaowen.md
  collated/test/mhq199657.md
  collated/test/tanhengyeow.md
Labels: collate, type.task

#83 Add more Persons
  src/main/java/seedu/address/model/FindResults.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/testutil/MoreTypicalPersons.java
Labels: type.enhancement

#84 Fixed typos to UG
  docs/UserGuide.adoc
Labels: type.documentation, type.task

#113 Add Project Portfolio Page
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/team/kexiaowen.adoc
Labels: type.documentation

#115 Fix issues and update documentation
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/DoubleUtil.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/JobApplied.java
  src/test/java/seedu/address/commons/util/DoubleUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/JobAppliedTest.java
  src/test/java/seedu/address/model/person/UniversityTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.bugfix

#117 v1.5 code administrative stuff
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindUtil.java
  src/main/java/seedu/address/logic/parser/PredicateUtil.java
  src/main/java/seedu/address/model/FindResults.java
  src/main/java/seedu/address/model/person/AllPredicate.java
Labels: type.enhancement, type.task

#118 V1.5 documentation
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AllPredicateComposition.png
  docs/images/FindCommandActivityDiagram.png
  docs/images/FindCommandComponents.png
  docs/images/FindCommandSequenceDiagram1.png
  docs/images/FindCommandSequenceDiagram2.png
  docs/team/tanhengyeow.adoc
Labels: type.documentation, type.task

#130 v1.5 test cases
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindUtil.java
  src/main/java/seedu/address/logic/parser/PredicateUtil.java
  src/main/java/seedu/address/model/FindResults.java
  src/main/java/seedu/address/model/person/AddressPredicate.java
  src/main/java/seedu/address/model/person/CommentPredicate.java
  src/main/java/seedu/address/model/person/EmailPredicate.java
  src/main/java/seedu/address/model/person/JobAppliedPredicate.java
  src/main/java/seedu/address/model/person/MajorPredicate.java
  src/main/java/seedu/address/model/person/NamePredicate.java
  src/main/java/seedu/address/model/person/PhonePredicate.java
  src/main/java/seedu/address/model/person/UniversityPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindUtilTest.java
  src/test/java/seedu/address/logic/parser/PredicateUtilTest.java
  src/test/java/seedu/address/model/FindResultsTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.task

#132 Update manual testing
  docs/DeveloperGuide.adoc
Labels: type.documentation

#134 v1.5-documentation
  collated/functional/Ang-YC.md
  collated/functional/kexiaowen.md
  collated/functional/mhq199657.md
  collated/functional/tanhengyeow.md
  collated/test/Ang-YC.md
  collated/test/kexiaowen.md
  collated/test/mhq199657.md
  collated/test/tanhengyeow.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/tanhengyeow.adoc
Labels: collate, type.documentation
