Repository CS2103JAN2018-W14-B3/main, pull requests merged in 2018-03, with the labels that each got.

#15 Add resume
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Resume.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/resources/resume/alex.pdf
  src/main/resources/resume/char.pdf
  src/test/data/ResumeTest/1 2.pdf
  src/test/data/ResumeTest/alice.pdf
  src/test/data/ResumeTest/benson.pdf
  src/test/data/ResumeTest/bob.pdf
  src/test/data/ResumeTest/daniel.pdf
  src/test/data/ResumeTest/fake.pdf
  src/test/data/ResumeTest/george.pdf
  src/test/data/ResumeTest/hoon.pdf
  src/test/data/ResumeTest/largeFile.pdf
  src/test/data/ResumeTest/valid.pdf
  src/test/data/ResumeTest/validPdf
  src/test/data/XmlUtilTest/hans.pdf
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/ResumeTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/resources/resume/alice.pdf
  src/test/resources/resume/amy.pdf
  src/test/resources/resume/benson.pdf
  src/test/resources/resume/bob.pdf
  src/test/resources/resume/daniel.pdf
  src/test/resources/resume/george.pdf
  src/test/resources/resume/hoon.pdf
Labels: type.enhancement

#17 Updated UI mockup
  docs/images/Ui.png
Labels: type.task

#18 Add rate command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RateCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Rating.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RateCommandParserTest.java
  src/test/java/seedu/address/model/person/RatingTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.enhancement

#16 Improved find command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/ExpectedGraduationYearContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/ExpectedGraduationYearContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: type.enhancement

#19 v1.1 documentation
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ANG-YC.png
  docs/images/kexiaowen.png
  docs/images/mhq199657.png
  docs/images/tanhengyeow.png
Labels: type.task

#21 Added interview command and field
  build.gradle
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/InterviewCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/InterviewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/InterviewDate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/resources/log4j.properties
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/InterviewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/InterviewCommandParserTest.java
  src/test/java/seedu/address/model/person/InterviewDateTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.enhancement

#23 Fix bug in storage component
  docs/AboutUs.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
Labels: type.bugfix

#24 Improve filter command - Part 1
  README.adoc
  docs/ContactUs.adoc
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterRange.java
  src/main/java/seedu/address/logic/parser/FilterUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/ExpectedGraduationYearBeforeKeywordPredicate.java
  src/main/java/seedu/address/model/person/ExpectedGraduationYearInKeywordsRangePredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterUtilTest.java
  src/test/java/seedu/address/model/person/ExpectedGraduationYearBeforeKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/ExpectedGraduationYearInKeywordsRangePredicateTest.java
  src/test/java/systemtests/FilterCommandSystemTest.java
Labels: type.enhancement

#28 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.documentation

#27 Added field named Major
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/InterviewCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/MajorTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.high, type.enhancement

#33 Improved find command (exact keyword search)
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindUtil.java
  src/main/java/seedu/address/model/person/MajorContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/MajorContainsKeywordsPredicateTest.java
Labels: status.ready, type.enhancement

#32 Add overall score for rating and add deleteRating command
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/DoubleUtil.java
  src/main/java/seedu/address/logic/commands/DeleteRatingCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteRatingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Rating.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/commons/util/DoubleUtilTest.java
  src/test/java/seedu/address/logic/commands/DeleteRatingCommandTest.java
  src/test/java/seedu/address/logic/commands/RateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteRatingCommandParserTest.java
  src/test/java/seedu/address/model/person/RatingTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: status.ready, type.enhancement

#46 add filter command description to Development Guide
  docs/DeveloperGuide.adoc
  docs/diagrams/FilterCommandSequenceDiagram.pptx
  docs/images/FilterCommandSequenceDiagram.png
Labels: type.documentation

#48 Add implementation of rate command in DeveloperGuide
  docs/DeveloperGuide.adoc
  docs/diagrams/RateCommandSequenceDiagram.pptx
  docs/images/RateCommandSequenceDiagram.png
Labels: type.documentation

#50 🌟 Rebuild user interface and Improve user experience
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/events/ui/InfoPanelChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/MaximizeAppRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/MinimizeAppRequestEvent.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/TitleBar.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/UiResizer.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HRTheme.css
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TitleBar.fxml
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/guitests/guihandles/InfoPanelHandle.java
  src/test/java/guitests/guihandles/InfoPanelUtil.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/guitests/guihandles/ResultDisplayHandle.java
  src/test/java/guitests/guihandles/StatusBarFooterHandle.java
  src/test/java/guitests/guihandles/TitleBarHandle.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/ui/InfoPanelTest.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/seedu/address/ui/TitleBarTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/seedu/address/ui/testutil/UiPartRule.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClockRule.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/WindowGuiTest.java
Labels: status.ready, type.epic

#52 Updated developer guide for find command
  docs/DeveloperGuide.adoc
  docs/diagrams/FindCommandSequenceDiagram.pptx
  docs/images/FindCommandSequenceDiagram.png
Labels: type.documentation

#57 Added field GradePointAverage
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRatingCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/InterviewCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/GradePointAverage.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/GradePointAverageTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.high, type.enhancement, type.story

#58 Add a new field JobApplied
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRatingCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/InterviewCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/JobApplied.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/JobAppliedTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: status.ready, type.enhancement

#61 v1.3 documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high, type.documentation, type.task

#60 Improved find command (wildcard search)
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindUtil.java
  src/main/java/seedu/address/logic/parser/PredicateUtil.java
  src/main/java/seedu/address/model/person/AddressContainsPrefixesPredicate.java
  src/main/java/seedu/address/model/person/AddressContainsSubstringsPredicate.java
  src/main/java/seedu/address/model/person/AddressContainsSuffixesPredicate.java
  src/main/java/seedu/address/model/person/AddressPredicate.java
  src/main/java/seedu/address/model/person/AllPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsPrefixesPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsSubstringsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsSuffixesPredicate.java
  src/main/java/seedu/address/model/person/EmailPredicate.java
  src/main/java/seedu/address/model/person/ExpectedGraduationYearContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/FieldPredicate.java
  src/main/java/seedu/address/model/person/MajorContainsPrefixesPredicate.java
  src/main/java/seedu/address/model/person/MajorContainsSubstringsPredicate.java
  src/main/java/seedu/address/model/person/MajorContainsSuffixesPredicate.java
  src/main/java/seedu/address/model/person/MajorPredicate.java
  src/main/java/seedu/address/model/person/NameContainsPrefixesPredicate.java
  src/main/java/seedu/address/model/person/NameContainsSubstringsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsSuffixesPredicate.java
  src/main/java/seedu/address/model/person/NamePredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsPrefixesPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsSubstringsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsSuffixesPredicate.java
  src/main/java/seedu/address/model/person/PhonePredicate.java
  src/test/java/seedu/address/model/person/ExpectedGraduationYearContainsKeywordsPredicateTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.high, type.enhancement, type.story

#64 Add a rating_sort command to sort current list of students based on overall rating
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/RatingSortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RatingSortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RateCommandTest.java
  src/test/java/seedu/address/logic/commands/RatingSortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: status.ready, type.enhancement

#65 Fix startup crash
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.high, type.bugfix
